# Configurações do Banco de Dados (Integração com MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mrjohn_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false